Update Enhancement v2
kaminaris/MaxDps-Shaman pull request #11
Opened 2022-11-28 22:30 UTC by BB00KK

Summary:
 - Add Elemental Spirits buffs, replace "FeralSpiritBuff" references that were trying to query this information but were instead just pulling the generic Feral Spirit buff
 - Add Overflowing Maelstrom support to Single Target and AOE
 - Lava Lash to spread Flame Shock (via Molten Assault)
 - Bug fixes

Known Issues:
- AoE Lava Lash does not query for Molten Assault talent, will fix asap

2022-12-01 22:58 UTC, kojakk approved these changes

2022-12-01 22:58 UTC, kojakk requested changes
need to update TOC file

2022-12-02 07:59 UTC, BB00KK commented
> need to update TOC file

what is the TOC file?  also I have a new stable revision ready to submit, should I close and submit a new pull request?

2022-12-02 19:05 UTC, kojakk commented
you should be able to update your pull request with the changes. There should be a MaxDps_Shaman.toc file

2024-02-01 00:59 UTC, closed without merging